### ISSUE TITLE
Module conflict when running setup.py

### ISSUE THREAD

**Issue by sjoro** [deeplycloudy/lmatools#20]
Installation of `lmatool` results in an error. Apparently the installation gets a conflict with the python `io`-module.

**Comment by deeplycloudy** [comment]
It looks like doing an absolute import will work around the problem

https://stackoverflow.com/questions/1224741/trying-to-import-module-with-the-same-name-as-a-built-in-module-causes-an-import

**Comment by sjoro** [comment]
Temporary fix that seems to work:
1) rename `io` under `lmatools` to, e.g., `lmaio`
2) modify `setup.py` by removing `lmatools.io` from packages
3) run `python setup.py install`
4) copy the renamed `lmaio` directory under the `lmatools` installation path with the name `io`

**Comment by tjlang** [comment]
FYI, I ran into a similar issue to this when installing from source in Python 3.7. I fixed it locally by basically renaming the io directory to something else and changing all the relevant import statements. If the submodule directories were placed into a master lmatools directory (e.g., like glmtools does), would that help?

**Comment by deeplycloudy** [comment]
@tjlang this is what the branch mentioned in the above package was meant to do. Does installing from that branch fix the problem for you?

**Comment by tjlang** [comment]
OK, @deeplycloudy, that fixed the install. Should that branch be made the master branch? It would make the package less confusing to install.

**Comment by deeplycloudy** [comment]
Thanks for the test. With that in mind, I went ahead with PR #24, and will close this issue.
